### ISSUE TITLE
About the dataset

### ISSUE THREAD

**Issue by Xnightwish** [mhxu1998/FlexCare#1]
Good brother, thank you very much for your work, I would like to inquire where can I download these datasets, I have been searching for a long time without any luck.

**Comment by mhxu1998** [comment]
Thanks for the interest in our work! The original MIMIC datasets are available at following links: 
- MIMIC-IV 2.0 https://physionet.org/content/mimiciv/2.0/
- MIMIC-CXR-JPG 2.0.0 https://physionet.org/content/mimic-cxr-jpg/2.0.0/
- MIMIC-IV-NOTE 2.2 https://physionet.org/content/mimic-iv-note/2.2/

Since we do not have the right to share these datasets, you need to request access for the MIMIC datasets on the official website. After downloading corresponding datasets, you can obtain the processed datasets and run the model according to the code we provide.
